### ISSUE TITLE
Easier Version Specification

### ISSUE THREAD

**Issue by tay10r** [tinyalsa/tinyalsa#123]
Currently, the version is specified in:

 - `src/Makefile`
 - `debian/changelog`
 - `include/tinyalsa/version.h`

When a new release is made, the risk is present of one of these files not getting updated. There should be an easier way of ensuring that all the versions get updated correctly. Perhaps a script to search and replace the version numbers in the specified files.

For example a script, `scripts/bump-version.sh` or `scripts/bump-version.py` that can be used to specify the version in these files.

```
./scripts/bump-version.sh minor
# or ./scripts/bump-version.sh major
# or ./scripts/bump-version.sh patch
```

The header file can be used to parse the current version.

**Comment by alexonea** [comment]
Are both cmake and plain makefiles used? Are there plans to continue only with one of them?

I was thinking of specifying the version in the main ```Makefile``` / ```CMakeLists.txt``` and generating the ```version.h``` header based on that. At the end of the build, maybe a check can be added in certain cases (e.g. for release builds) and display a warning in case ```debian/changelog``` stayed behind. If we need more strict rules, the final check can even force the release builds to fail until ```debian/changelog``` is updated.

I wouldn't update ```debian/changelog``` automatically via a script or by auto-generating bits of it since, in my opinion, it should always require "a human touch" (but that's just me).

**Comment by tay10r** [comment]
@alexonea What about a program like [bumpversion](https://github.com/peritus/bumpversion)?

I agree with the `debian/changelog` warning, that would be helpful.

**Comment by alexonea** [comment]
@tay10r I created a draft pull request. I am not sure about using a 3rd party script like [bumpversion](https://github.com/peritus/bumpversion) or writing our own. I already implemented a simple version "management" script capable of doing all we need, but I feel that we are not reusing as much as we could. On the other hand, do we care about an extra dependency?

I detailed in the draft a proposal for how I imagine the version specification scheme. Let me know what you think and if it also fits your view.
