### ISSUE TITLE
How to cross-compile properly?

### ISSUE THREAD

**Issue by brunosmmm** [tinyalsa/tinyalsa#145]
Hello, I want to cross-compile tinyalsa to an arm target, however compilation of anything but the library itself fails in my system due to implicit Makefile rules like these: 
https://github.com/tinyalsa/tinyalsa/blob/5389c1f796ea153232a582bd28e73be43638a124/utils/Makefile#L22

On my system at least, make resolves the ```-ldl``` to my native architecture and I'll get something like:
```
my-cross-gcc -L ../src -pie  tinyplay.o ../src/libtinyalsa.a /usr/lib/x86_64-linux-gnu/libdl.so -o tinyplay
/usr/lib/x86_64-linux-gnu/libdl.so: file not recognized: file format not recognized
```
I don't understand what is the point of a CROSS_COMPILE variable in the Makefile if utils, examples, etc can't be built properly by setting it?

The build can be easily fixed by having an explicit rule, for instance, in the utils subfolder:

```makefile
tinyplay: tinyplay.o libtinyalsa.a
	$(CC) -o $@ $^ -ldl
```
Is there a clear reason for not doing this? If not, I'd be glad to submit a pull request which fixes these.

**Comment by tay10r** [comment]
> I don't understand what is the point of a CROSS_COMPILE variable in the Makefile if utils, examples, etc can't be built properly by setting it?

Right, clearly this is a bug and you're suppose to be able to build the examples. I think this happens because GNU make tries to resolve dependencies that look like libraries itself, instead of relying on the compiler - a useful feature for project libraries but not so much system ones (in this case.)

I'll be happy to accept a PR to fix this. I think the probably way to handle this is to do something like this:

```
tinyplay tinycap tinypcminfo: LDLIBS+=-ldl
```
That should bypass the dependency resolving that `make` does and leave it to the compiler or linker.
If that doesn't work, maybe the way you suggested:

```
%: %.o libtinyalsa.a
  $(CC) -o $@ $^ -ldl
```

This error is due to the recent addition of plugins we've added to the project. It still needs a bit of work because currently there's no way of disabling the `dl` requirement when omitting plugin support. In the mean time, hopefully one of those rules fixes the cross compile issue.

**Comment by brunosmmm** [comment]
I tested your proposed solution, seems to work great, so I made a pull request. Thanks
