### ISSUE TITLE
New tag/release?

### ISSUE THREAD

**Issue by Minecrell** [tinyalsa/tinyalsa#154]
The last tag/release is from 3 years ago, there were many fixes and new features since then. Are there any plans to make a tag a new release? This would make packaging more easy in other distributions.

Thanks!

**Comment by tay10r** [comment]
Hey! Yes the next release will be a new major version. There's a binary incompatible change due to the dl dependency and a change to the pcm format enumeration. Due to this, I'd like to investigate what other improvements I can make that don't require binary compatibility. I'll leave this open and give an update soon.

**Comment by tay10r** [comment]
Just bumped the version to 2.0.0. I'll make a tag/release for it as soon as I feel confident that it has binary compatibility with Google's copy of TinyALSA. It does have breaking changes from the last release though. As I mentioned before, the PCM format enumeration changed. There's also the additional requirement to link with `-ld`.

**Comment by Minecrell** [comment]
Thanks for making a new tag!
