### ISSUE TITLE
Tinyalsa open failed when a abnormal  close

### ISSUE THREAD

**Issue by FeeiSZ** [tinyalsa/tinyalsa#99]
There is something wrong with TINYALSA based program. We can not shut down TINYALSA on ours  initiative in both case ,first ,stop the program using the task manager，second，exit the program without a response.therefore ,after restart the program，we failed to open PCM succesfully.We wonder if there are some problems with OCCI.Do you have any suggestions about this problems?

**Comment by tay10r** [comment]
What error message are you getting? What made you narrow your problem down to TinyALSA?

**Comment by FeeiSZ** [comment]
My functions as follow:
/*
 * start recorder
 */
wtk_tinyalsa_record_t* wtk_tinyalsa_record_start(void *h,char *dev,int sample_rate,int channel,int buf_time)
{
	wtk_tinyalsa_record_t* r=0;
	int card;
	int ret=-1;

	r = calloc(1, sizeof(*r));
	if (!r) {goto end;}
	/*
	 * set params
	 */
	r->config.channels = channel;
	r->config.rate = sample_rate;
	r->config.period_size = buf_time*sample_rate/1000;
	r->config.period_count = 4;
	r->config.format = PCM_FORMAT_S16_LE;
	r->config.start_threshold = 0;
	r->config.stop_threshold = 0;
	r->config.silence_threshold = 0;

	//wtk_debug("%s\n",dev);
	card=atoi(dev);
	r->pcm=0;
	//wtk_debug(" %d  %d %d %d\n",card,sample_rate,channel,buf_time);
	r->pcm = pcm_open(card, 0, PCM_IN, &r->config);
	if(!r->pcm || !pcm_is_ready(r->pcm)){
		wtk_debug("%s\n",pcm_get_error(r->pcm));
		goto end;
	}
	pcm_frames_to_bytes(r->pcm,pcm_get_buffer_size(r->pcm));

	ret=pcm_start(r->pcm);
	if(ret!=0){
		wtk_debug("%s.\n",pcm_get_error(r->pcm));
		goto end;
	}

	ret=0;
end:
	if(ret!=0){
		if(r){
			pcm_stop(r->pcm);
			pcm_close(r->pcm);
			free(r);
			r=0;
		}
	}else{
		r->pcm2=r->pcm;
		FD_ZERO(&(r->r_set));
		FD_SET(r->pcm2->fd,&(r->r_set));
		FD_ZERO(&(r->e_set));
		FD_SET(r->pcm2->fd,&(r->e_set));
	}
	return r;
}

/*
 * stop recorder
 */
int wtk_tinyalsa_record_stop(void*h,wtk_tinyalsa_record_t* r)
{
	if(r){
		FD_CLR(r->pcm2->fd,&(r->r_set));
		FD_CLR(r->pcm2->fd,&(r->e_set));
		pcm_stop(r->pcm);
		pcm_close(r->pcm);
		free(r);
	}
	return 0;
}

after stop the program using the task manager or exit the program without a response.restart the recorder and I will get error [cannot set hw params: I/O error].

**Comment by tay10r** [comment]
I'll take a closer look later today and see if I notice anything. Is it possible to build your code with debug symbols and run it under [valgrind](http://valgrind.org/)? If you can do that and show the output, it would be helpful.

**Comment by FeeiSZ** [comment]
Thanks for your help.My program runs on android by JNI .And the Error is occured when the Android Program is  exited by accident,so, the Func [wtk_tinyalsa_record_stop] will not be called. I think the point is Tinyalsa  is not normally close .  And at this time .I  plug out and plug in the USB Audio equipment,the program will run successful.  
   I,m sorry for my poor english.

**Comment by tay10r** [comment]
No worries about the English! I wish I knew more languages than just one!

Are you saying that TinyALSA was not the cause of your problem?

**Comment by FeeiSZ** [comment]
yeah,the Program is runing regularly if the Android Program not Exited abnormal.

**Comment by FeeiSZ** [comment]
And the Problem is happened when luanch the Andoird program again after accident exit.

**Comment by tay10r** [comment]
Okay. It sounds like this is not a TinyALSA problem, so I'm closing the issue.

**Comment by FeeiSZ** [comment]
@tay10r thank you.

**Comment by MolchanovDmitry** [comment]
@FeeiSZ Hello. Did you solve the issue? I have the same problem:
ioctl(pcm->fd, SNDRV_PCM_IOCTL_HW_PARAMS, &params)
 returns 5 instead of 0 after incorrect pcm closing.

**Comment by pasqualirb** [comment]
@MolchanovDmitry Are you sure the `HW_PARAMS` `ioctl()` system call return positive `5`? If yes, what is the version of Linux kernel that this behavior occurs?

Can you describe better the "incorrect pcm closing"? Does `close()` system call return an error or it's the application exiting without calling `close()`?

Notice that I'm not talking about the TinyALSA wrappers/functions like `pcm_open()` and `pcm_close()`, but rather `open()` and `close()` system calls.

**Comment by MolchanovDmitry** [comment]
@pasqualirb Thanks for your answer.
Yes, I'm sure, because I'd took this value from the logs.  Linux kernel: 3.14.29(Android 7.1.2).

So, what I do. I'm using forсe close of my application from the android studio. Application closes, but it doesn't executes pcm_close(). After that, I can't read anything from pcm, until I restart Android system.

Sorry, but i have a little misunderstanding - you said about "open() and close() system calls", but which one does you mean? Can you promt me, where and when they are called?

**Comment by pasqualirb** [comment]
Cc: @tiwai

> Yes, I'm sure, because I'd took this value from the logs. Linux kernel: 3.14.29(Android 7.1.2).

The `HW_PARAMS` `ioctl()` returning `5` is rather awkward. I've visited [the code](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/sound/core/pcm_native.c?h=v3.14.29#n380) for version 3.14.29 and it does not return positive values (`PTR_ERR()` is no exception). Also, the `ioctl()` system call [does not seem](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/fs/ioctl.c?h=v3.14.29#n604) to have any influence. Further investigation should be done, though. Here is a [diff](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/diff/sound/core/pcm_native.c?id=master&id2=v3.14.29) between master and v3.14.29 .

If the sign is hidden/inverted by the logger, `5` is `EIO`. However, this error is not returned by `snd_pcm_hw_params()`. What is the logger application?

The issue should definitely not be related to TinyALSA. For debugging: Have you updated TinyALSA? What version are you using?

> So, what I do. I'm using forсe close of my application from the android studio. Application closes, but it doesn't executes pcm_close(). After that, I can't read anything from pcm, until I restart Android system.

This is strange. Does the issue always occur when a given code is run? Could you post a minimal C code that reproduce it?

Can you post the output of `cat /proc/asound/<your_card>/<pcm_device>/sub0/{hw_params,status}` just after the problem arises?

By the way, I've encountered an issue some time ago that apparently breaks ALSA and is similar to [1509211](https://bugzilla.redhat.com/show_bug.cgi?id=1509211) from Red Hat Bugzilla. The kernel version was 4.13.16 .

> Sorry, but i have a little misunderstanding - you said about "open() and close() system calls", but which ones does you mean? Can you promt me, where and when they are called?

My fault. I should have mentioned only `close()`. This is called in `pcm_close()` to close the file descriptor, eventually freeing/releasing ALSA stuff. Sorry.

**Comment by pasqualirb** [comment]
@MolchanovDmitry In addition to the above, can you post the output of `dmesg | tail` just after the issue?

**Comment by tay10r** [comment]
@pasqualirb Thanks for helping out with this.

@MolchanovDmitry I'll reopen this until this gets figured out.

**Comment by MolchanovDmitry** [comment]
Oh, I'm sorry, your are right, ioctl() returns -1. 

> The issue should definitely not be related to TinyALSA. For debugging: Have you updated TinyALSA? What version are you using?

version.h contains #define TINYALSA_VERSION_STRING "1.1.1", is this the version you asking for?

> This is strange. Does the issue always occur when a given code is run? 

Usually, I have no problems with opening pcm, but I'll get that issue if some system error crashs my application, and in consequence of this, it wouldn't call pcm_close().

>  Can you post the output of cat /proc/asound/<your_card>/<pcm_device>/sub0/{hw_params,status} just after the problem arises?

p212:/ # cat /proc/asound/card1/pcm0c/sub0/hw_params 
closed
p212:/ # cat /proc/asound/card1/pcm0c/sub0/status 
closed
Also, after force closing, the application lsof /dev/snd/pcmC1D0c returns nothing

> This is called in pcm_close() to close the file descriptor, eventually freeing/releasing ALSA stuff.
Can you give advice what should I do to freeing/releasing ALSA stuff? 

My C code + dmesg
https://github.com/MolchanovDmitry/Tinycap

**Comment by pasqualirb** [comment]
> Oh, I'm sorry, your are right, ioctl() returns -1.

Ok, this is `EIO` (5) as your code exposed. After some search, it seems that the only place in the `HW_PARAMS` `ioctl()` execution that may return `EIO` is the `hw_params()` driver callback, called by `snd_pcm_hw_params()`, `sound/core/pcm_native.c`. Notice I was wrong when I said `EIO` is not returned by `snd_pcm_hw_params()`. This is likely to be a driver issue. E.g. the USB driver may return `EIO` in `set_format()`, `sound/usb/pcm.c`, which is called by `snd_usb_hw_params()` (the `hw_params()` callback).

What is the output of `cat /proc/asound/modules`?

Side note: In your `dmesg` snippet, the message `usb 1-2.3: Not enough bandwidth for altsetting 0` is a hint if you are using an USB sound card. However, I wonder if this is the case as there seems to be no message of ALSA subsystem.

Also in your `dmesg` snippet, SELinux is denying some system calls. SELinux access errors are generally `EACCES` (13). Have you experienced this error? Have you changed some SELinux setting?

> version.h contains #define TINYALSA_VERSION_STRING "1.1.1", is this the version you asking for?

Yes.

> Usually, I have no problems with opening pcm, but I'll get that issue if some system error crashs my application, and in consequence of this, it wouldn't call pcm_close().

What system error? What happens?

> p212:/ # cat /proc/asound/card1/pcm0c/sub0/hw_params
> closed
> p212:/ # cat /proc/asound/card1/pcm0c/sub0/status
> closed
> Also, after force closing, the application lsof /dev/snd/pcmC1D0c returns nothing

This is the expected behavior.

> My C code + dmesg
> https://github.com/MolchanovDmitry/Tinycap

Thank you!

**Comment by MolchanovDmitry** [comment]
p212:/ # cat /proc/asound/modules
    tmp-mksh: cat: /proc/asound/modules: No such file or directory

> is a hint if you are using an USB sound card

Your are quite right. I'm using usb. Sorry, I had to start from this.

Thank you very much for the tips. I solved it this way:

    echo usb1 > /sys/bus/usb/drivers/usb/unbind
    echo usb1 > /sys/bus/usb/drivers/usb/bind

**Comment by pasqualirb** [comment]
> Thank you very much for the tips. I solved it this way:
> 
> ```
> echo usb1 > /sys/bus/usb/drivers/usb/unbind
> echo usb1 > /sys/bus/usb/drivers/usb/bind
> ```

This issue seems to be related/similar to:

- USB: Not enough bandwidth for new device state <https://bugzilla.redhat.com/show_bug.cgi?id=1411604>

- xhci: Not enough bandwidth for new device state <https://lkml.org/lkml/2018/2/28/1244>

- external USB-Speaker and "Not enough bandwidth for altsetting 1" <https://www.spinics.net/lists/linux-usb/msg128181.html>

- (different from the above) external USB-Speaker and "Not enough bandwidth for altsetting 1" <https://marc.info/?l=linux-usb&m=152434834500316>

- Error: cannot submit urb 0, error -28: not enough bandwidth - when starting USB capture device connected via hub <https://bugzilla.kernel.org/show_bug.cgi?id=47201>

- usb soundcard fails on usb3 port while working on raspberry PI2 <https://bugzilla.kernel.org/show_bug.cgi?id=200149>

- xHCI bandwidth error with USB webcam <https://patchwork.linuxtv.org/patch/3170/>

I don't know whether this has been solved, but it seems some work has been done recently regarding the alternate settings and bandwidth allocation:

- Re: usb HC busted? <https://marc.info/?l=linux-usb&m=153208701623882>

- Re: [PATCH] usb: Avoid use-after-free by flushing endpoints early in usb_set_interface() <https://marc.info/?l=linux-usb&m=153597805732024>

Here is a search for "Not enough bandwidth for altsetting" in linux-usb mailing list: <https://marc.info/?l=linux-usb&w=2&r=1&s=Not+enough+bandwidth+for+altsetting&q=b>.

**Comment by tay10r** [comment]
@pasqualirb It seems that this isn't a TinyALSA issue. I'll leave this open for a bit longer but I plan on closing it.

**Comment by pasqualirb** [comment]
> @pasqualirb It seems that this isn't a TinyALSA issue. I'll leave this open for a bit longer but I plan on closing it.

Definitely it's not a TinyALSA issue. I agree in leaving this open for a while. Some developer may find this and come up with a solution to the real issue if it hasn't been done.

**Comment by tay10r** [comment]
@FeeiSZ @pasqualirb I'm closing this, I think it's been open long enough.
